apiVersion: v1
kind: Service
metadata:
  labels:
    service: loc-event-api
  name: loc-event-api
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
    nodePort: 30005
  selector:
    service: loc-event-api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: loc-event-api
  name: loc-event-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: loc-event-api
  template:
    metadata:
      labels:
        service: loc-event-api
    spec:
      containers:
      - image: praemisit/loc-event-api:latest
        name: loc-event-api-container
        imagePullPolicy: Always
        env:
        - name: KAFKA_URL
          valueFrom:
            configMapKeyRef:
              name: kafka-configmap
              key: KAFKA_URL
        - name: KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: kafka-configmap
              key: KAFKA_TOPIC
        - name: PYTHONUNBUFFERED
          value: '0'
      restartPolicy: Always