# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: locEvent.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='locEvent.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0elocEvent.proto\"F\n\x0fLocEventMessage\x12\x0e\n\x06userId\x18\x01 \x01(\x05\x12\x10\n\x08latitude\x18\x02 \x01(\x05\x12\x11\n\tlongitude\x18\x03 \x01(\x05\x32?\n\x0fLocEventService\x12,\n\x06\x43reate\x12\x10.LocEventMessage\x1a\x10.LocEventMessageb\x06proto3'
)




_LOCEVENTMESSAGE = _descriptor.Descriptor(
  name='LocEventMessage',
  full_name='LocEventMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='LocEventMessage.userId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='LocEventMessage.latitude', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='LocEventMessage.longitude', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=88,
)

DESCRIPTOR.message_types_by_name['LocEventMessage'] = _LOCEVENTMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LocEventMessage = _reflection.GeneratedProtocolMessageType('LocEventMessage', (_message.Message,), {
  'DESCRIPTOR' : _LOCEVENTMESSAGE,
  '__module__' : 'locEvent_pb2'
  # @@protoc_insertion_point(class_scope:LocEventMessage)
  })
_sym_db.RegisterMessage(LocEventMessage)



_LOCEVENTSERVICE = _descriptor.ServiceDescriptor(
  name='LocEventService',
  full_name='LocEventService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=90,
  serialized_end=153,
  methods=[
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='LocEventService.Create',
    index=0,
    containing_service=None,
    input_type=_LOCEVENTMESSAGE,
    output_type=_LOCEVENTMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_LOCEVENTSERVICE)

DESCRIPTOR.services_by_name['LocEventService'] = _LOCEVENTSERVICE

# @@protoc_insertion_point(module_scope)
